# Generated by Django 6.1 on 2026-08-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
